### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by EmperorPenguin18** [stetre/moonchipmunk#1]
I noticed that this library only supports Linux, but a lot of the other moonlibs support both. I am a Linux user myself, but in case users of my software (which use this library) want to use Windows I was wondering if there were plans to add that?

**Comment by stetre** [comment]
Same answer as for your [question about MoonVulkan](https://github.com/stetre/moonvulkan/issues/5#issuecomment-1080033455).

(I suspect that this one may already work as it is,  but I've never tried it).

**Comment by stetre** [comment]
Now it should work on Windows using MSYS2/MinGW. See issue #5.
